sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ravi/docker-react Dockerfile.dev .

script:
  - docker run -e CI=true ravi/docker-react npm run test -- --coverage